# Pytorch zero to gan : Assignment 1


An short introduction about PyTorch and about the chosen functions. 
- torch.remainder
- torch.add
- torch.arange
- torch.reshape
- torch.transpose

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.remainder

torch.remainder computes the element-wise remainder of division.

Example -- 01

In [2]:
torch.remainder(torch.tensor([-5., -3, -5, 4, 9, 7]), 2)

tensor([1., 1., 1., 0., 1., 1.])

Above matrix shows the Remainder after dividing by 2.

Example -- 02

In [3]:
torch.remainder(torch.tensor([-35., -5, -20, 22, 16, 9]), -3.5)

tensor([ 0.0000, -1.5000, -2.5000, -2.5000, -1.5000, -1.5000])

In [4]:
torch.remainder(torch.tensor([-35., -5, -20, 22, 16, 9]), 35)

tensor([ 0., 30., 15., 22., 16.,  9.])

## Function 2 - torch.add()

Adds the scalar other to each element of the input input and returns a new resulting tensor.


Example 1:

In [5]:
a = torch.randn(4)
a

tensor([-0.1161, -1.4664,  0.5835, -1.2395])

In [6]:
torch.add(a, 10)

tensor([ 9.8839,  8.5336, 10.5835,  8.7605])

torch.add Adds the value into the tensor, in this case  is added to the tensor.

Example 2

In [7]:
b = torch.randn(5)
b

tensor([ 1.1708,  0.1533,  0.2234, -0.5631,  0.7947])

In [8]:
torch.add(b, -50)

tensor([-48.8292, -49.8467, -49.7766, -50.5631, -49.2053])

Example 3

In [9]:
torch.add(b ,'30')

TypeError: add(): argument 'other' (position 2) must be Tensor, not str

The value to be added must be in Tensor.

## Function 3 - torch.arange()

Returns a 1-D tensor 



In [10]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In this case output is by default 10 integers with step 1.

Example : 2

In [11]:
>>> torch.arange(1, 4, 2)

tensor([1, 3])

In this case output tensor is 1 and 3 with step of 2 as mentioned.

Example: 3


In [12]:
>>> torch.arange([1, 2.5, 0.5])

TypeError: arange(): argument 'end' (position 1) must be Number, not list

Arrange function can take arguments only in numbers not in list.

## Function 4 - torch.reshape

Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. 

Example: 1

In [13]:
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

Tensor of 4 reshaped into 2*2 matrix.

Example 2 

In [14]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

Tensor of 2*2 is reshaped.

Example : 3

In [15]:
c = torch.tensor([[0, 3], [42, 3], [45, 35]])
torch.reshape(c, (1,))

RuntimeError: shape '[1]' is invalid for input of size 6

## Function 5 - torch.transpose

Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

Example : 1

In [16]:
x = torch.randn(2, 3)
x

tensor([[ 0.7956,  1.1743, -1.9201],
        [ 0.4361,  1.2069, -0.3597]])

In [17]:
torch.transpose(x, 0, 1)

tensor([[ 0.7956,  0.4361],
        [ 1.1743,  1.2069],
        [-1.9201, -0.3597]])

We transposed 2 * 3 matrix into 3*2.

Example 2

In [18]:
y = torch.randn(3, 2)
y

tensor([[ 2.1100, -2.4968],
        [-0.5304, -0.5156],
        [-1.1932,  0.2597]])

In [19]:
torch.transpose(y, 1,0)

tensor([[ 2.1100, -0.5304, -1.1932],
        [-2.4968, -0.5156,  0.2597]])

We transposed 3*2 matrix into 2*3.

Example :3

In [20]:
z = torch.randn(5, 2)
z

tensor([[-0.1709,  1.6781],
        [-0.5923,  0.3951],
        [ 0.0362, -1.3191],
        [ 0.4708, -0.0331],
        [-0.7692,  0.5952]])

In [21]:
torch.transpose(z, 2,6)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

For transpose we have to give the dimensions in the range.

## Conclusion

In this notebook we covered the basic PyTorch functions like torch.remainder, torch.add, torch.arange, torch.reshape,torch.transpose,

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [22]:
!pip install jovian --upgrade --quiet

In [23]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
